unit TestController.SolicitacaoMatricula;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  System.Generics.Collections,
  Controller.SolicitacaoMatricula.Intf,
  Controller.SolicitacaoMatricula.Aluno,
  Controller.SolicitacaoMatricula.Atendente,
  Controller.SolicitacaoMatricula.Coordenador,
  entity.curso;

type
  TestISolicitacaoMatricula = class(TTestCase)
  strict private
  published
    procedure TestSolicitarAutorizacaoMatricula();
  end;

implementation

procedure TestISolicitacaoMatricula.TestSolicitarAutorizacaoMatricula;
var
  LSolicitacaoMatriculaAluno: ISolicitacaoMatricula;
  LSolicitacaoMatriculaAtendente: ISolicitacaoMatricula;
  LSolicitacaoMatriculaCoordenador: ISolicitacaoMatricula;
  LCurso: TCurso;
  LListaDocumentos: TObjectList<TObject>;
begin
  LListaDocumentos := TObjectList<TObject>.Create();
  LCurso := TCurso.Create();
  LCurso.descricao := 'Pós Delphi - UNOESC';

  LSolicitacaoMatriculaAluno := TSolicitacaoMatriculaAluno.Create();
  LSolicitacaoMatriculaAtendente := TSolicitacaoMatriculaAtendente.Create();
  LSolicitacaoMatriculaCoordenador := TSolicitacaoMatriculaCoordenador.Create();

  LSolicitacaoMatriculaAluno.SetSucessor(LSolicitacaoMatriculaAtendente);
  LSolicitacaoMatriculaAtendente.SetSucessor(LSolicitacaoMatriculaCoordenador);

  CheckTrue(LSolicitacaoMatriculaAluno.SolicitarAutorizacaoMatricula(LListaDocumentos, LCurso),
    'A matrícula no curso foi aprovada.');
end;

initialization
  RegisterTest(TestISolicitacaoMatricula.Suite());

end.
